---
title: About the sessions
format:
  theme-html:
    toc: false
---


## AI for Ecologists

The [National Center for Ecological Analysis and Synthesis (NCEAS)](https://www.nceas.ucsb.edu/), a research affiliate of UCSB,  is now celebrating its 30th year.  As part of this celebration, NCEAS is focusing on a theme of "AI for the Planet," and as members of the [NCEAS Learning Hub](https://www.nceas.ucsb.edu/learning-hub) we have designed this set of informal interactive workshop sessions in support of that theme.  In these sessions, we will explore uses of generative artificial intelligence (genAI or simply AI) such as ChatGPT and GitHub Copilot to help support NCEAS residents and others in applying AI tools to research, analysis, and writing.  We are by no means experts in the design and application of AI, we are just curious and excited (perhaps a bit apprehensive) about the possibilities these new tools offer.  These sessions may eventually become formal modules available for various NCEAS Learning Hub courses, but for now we just want to encourage the NCEAS community to explore the benefits and pitfalls these tools offer.


## NCEAS Expertise

NCEAS is a leading expert on interdisciplinary data science and works collaboratively to answer the world's largest and most complex questions. The NCEAS approach leverages existing data and employs a team science philosophy to squeeze out all potential insights and solutions efficiently - this is called [synthesis science](https://www.nceas.ucsb.edu/our-approach).

NCEAS has 30 years of success with this model among working groups and environmental professionals.  In conjunction with the NCEAS Learning Hub, we are excited to pass along skills, workflows, and mindsets to help the NCEAS community better understand the implications of AI for the Planet.


<!-- *June 10 - 13, 2024* -->

:::{.callout-tip}
### Learning Objectives

- Practice strategies for using AI tools effectively and responsibly in coding, analysis, and research.
- Explore the ethical implications of using AI in research and how to navigate them.
- Feel comfortable with using various AI tools in your own work.
:::


## Code of Conduct

By participating in this activity you agree to abide by the [NCEAS Code of Conduct](https://www.nceas.ucsb.edu/sites/default/files/2021-11/NCEAS_Code-of-Conduct_Nov2021_0.pdf).

## About this book

These written materials are the result of a continuous and collaborative effort at NCEAS to help researchers make their work more transparent and reproducible. This work began in the early 2000's, and reflects the expertise and diligence of many, many individuals. The primary authors are listed in the citation below, with additional contributors recognized for their role in developing previous iterations of these or similar materials.

This work is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/).

**Citation:** Casey O'Hara and Li Kui (2025), AI for Ecologists. URL <https://nceas-learning-hub.github.io/ai_for_nceas>.

**Additional contributors:** tbd

This is a Quarto book. To learn more about Quarto books visit <https://quarto.org/docs/books>.




